name: manage-azure-policy-d06dc0a0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'KeyVault/initiatives/KeyVault_Security_Baseline_32a80d25f09743bd842cf6b8/**'
#      - .github/workflows/manage-azure-policy-d06dc0a0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d06dc0a0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          KeyVault/initiatives/KeyVault_Security_Baseline_32a80d25f09743bd842cf6b8/**
